// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ric-geo/ricgeo.proto

package ricgeo

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{0}
}

func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (m *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(m, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type WatchRequest struct {
	Oid       string `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	EventType string `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Types that are valid to be assigned to Type:
	//	*WatchRequest_Fences
	//	*WatchRequest_Routes
	Type                 isWatchRequest_Type `protobuf_oneof:"type"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *WatchRequest) Reset()         { *m = WatchRequest{} }
func (m *WatchRequest) String() string { return proto.CompactTextString(m) }
func (*WatchRequest) ProtoMessage()    {}
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{1}
}

func (m *WatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchRequest.Unmarshal(m, b)
}
func (m *WatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchRequest.Marshal(b, m, deterministic)
}
func (m *WatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchRequest.Merge(m, src)
}
func (m *WatchRequest) XXX_Size() int {
	return xxx_messageInfo_WatchRequest.Size(m)
}
func (m *WatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchRequest proto.InternalMessageInfo

func (m *WatchRequest) GetOid() string {
	if m != nil {
		return m.Oid
	}
	return ""
}

func (m *WatchRequest) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

type isWatchRequest_Type interface {
	isWatchRequest_Type()
}

type WatchRequest_Fences struct {
	Fences *RpeatedFence `protobuf:"bytes,3,opt,name=fences,proto3,oneof"`
}

type WatchRequest_Routes struct {
	Routes *RepeatedRoute `protobuf:"bytes,4,opt,name=routes,proto3,oneof"`
}

func (*WatchRequest_Fences) isWatchRequest_Type() {}

func (*WatchRequest_Routes) isWatchRequest_Type() {}

func (m *WatchRequest) GetType() isWatchRequest_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *WatchRequest) GetFences() *RpeatedFence {
	if x, ok := m.GetType().(*WatchRequest_Fences); ok {
		return x.Fences
	}
	return nil
}

func (m *WatchRequest) GetRoutes() *RepeatedRoute {
	if x, ok := m.GetType().(*WatchRequest_Routes); ok {
		return x.Routes
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*WatchRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _WatchRequest_OneofMarshaler, _WatchRequest_OneofUnmarshaler, _WatchRequest_OneofSizer, []interface{}{
		(*WatchRequest_Fences)(nil),
		(*WatchRequest_Routes)(nil),
	}
}

func _WatchRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*WatchRequest)
	// type
	switch x := m.Type.(type) {
	case *WatchRequest_Fences:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Fences); err != nil {
			return err
		}
	case *WatchRequest_Routes:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Routes); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("WatchRequest.Type has unexpected type %T", x)
	}
	return nil
}

func _WatchRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*WatchRequest)
	switch tag {
	case 3: // type.fences
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RpeatedFence)
		err := b.DecodeMessage(msg)
		m.Type = &WatchRequest_Fences{msg}
		return true, err
	case 4: // type.routes
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RepeatedRoute)
		err := b.DecodeMessage(msg)
		m.Type = &WatchRequest_Routes{msg}
		return true, err
	default:
		return false, nil
	}
}

func _WatchRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*WatchRequest)
	// type
	switch x := m.Type.(type) {
	case *WatchRequest_Fences:
		s := proto.Size(x.Fences)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WatchRequest_Routes:
		s := proto.Size(x.Routes)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type RpeatedFence struct {
	Fences               []*Fence `protobuf:"bytes,1,rep,name=fences,proto3" json:"fences,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpeatedFence) Reset()         { *m = RpeatedFence{} }
func (m *RpeatedFence) String() string { return proto.CompactTextString(m) }
func (*RpeatedFence) ProtoMessage()    {}
func (*RpeatedFence) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{2}
}

func (m *RpeatedFence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpeatedFence.Unmarshal(m, b)
}
func (m *RpeatedFence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpeatedFence.Marshal(b, m, deterministic)
}
func (m *RpeatedFence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpeatedFence.Merge(m, src)
}
func (m *RpeatedFence) XXX_Size() int {
	return xxx_messageInfo_RpeatedFence.Size(m)
}
func (m *RpeatedFence) XXX_DiscardUnknown() {
	xxx_messageInfo_RpeatedFence.DiscardUnknown(m)
}

var xxx_messageInfo_RpeatedFence proto.InternalMessageInfo

func (m *RpeatedFence) GetFences() []*Fence {
	if m != nil {
		return m.Fences
	}
	return nil
}

type Fence struct {
	GeofenceId           string   `protobuf:"bytes,1,opt,name=geofence_id,json=geofenceId,proto3" json:"geofence_id,omitempty"`
	ShapeId              string   `protobuf:"bytes,2,opt,name=shape_id,json=shapeId,proto3" json:"shape_id,omitempty"`
	RoomId               string   `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fence) Reset()         { *m = Fence{} }
func (m *Fence) String() string { return proto.CompactTextString(m) }
func (*Fence) ProtoMessage()    {}
func (*Fence) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{3}
}

func (m *Fence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fence.Unmarshal(m, b)
}
func (m *Fence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fence.Marshal(b, m, deterministic)
}
func (m *Fence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fence.Merge(m, src)
}
func (m *Fence) XXX_Size() int {
	return xxx_messageInfo_Fence.Size(m)
}
func (m *Fence) XXX_DiscardUnknown() {
	xxx_messageInfo_Fence.DiscardUnknown(m)
}

var xxx_messageInfo_Fence proto.InternalMessageInfo

func (m *Fence) GetGeofenceId() string {
	if m != nil {
		return m.GeofenceId
	}
	return ""
}

func (m *Fence) GetShapeId() string {
	if m != nil {
		return m.ShapeId
	}
	return ""
}

func (m *Fence) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type RepeatedRoute struct {
	Ids                  []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepeatedRoute) Reset()         { *m = RepeatedRoute{} }
func (m *RepeatedRoute) String() string { return proto.CompactTextString(m) }
func (*RepeatedRoute) ProtoMessage()    {}
func (*RepeatedRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{4}
}

func (m *RepeatedRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepeatedRoute.Unmarshal(m, b)
}
func (m *RepeatedRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepeatedRoute.Marshal(b, m, deterministic)
}
func (m *RepeatedRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepeatedRoute.Merge(m, src)
}
func (m *RepeatedRoute) XXX_Size() int {
	return xxx_messageInfo_RepeatedRoute.Size(m)
}
func (m *RepeatedRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_RepeatedRoute.DiscardUnknown(m)
}

var xxx_messageInfo_RepeatedRoute proto.InternalMessageInfo

func (m *RepeatedRoute) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type ControlRequest struct {
	Oid                  string   `protobuf:"bytes,1,opt,name=oid,proto3" json:"oid,omitempty"`
	Time                 *Time    `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Circle               *Circle  `protobuf:"bytes,3,opt,name=circle,proto3" json:"circle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControlRequest) Reset()         { *m = ControlRequest{} }
func (m *ControlRequest) String() string { return proto.CompactTextString(m) }
func (*ControlRequest) ProtoMessage()    {}
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{5}
}

func (m *ControlRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControlRequest.Unmarshal(m, b)
}
func (m *ControlRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControlRequest.Marshal(b, m, deterministic)
}
func (m *ControlRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControlRequest.Merge(m, src)
}
func (m *ControlRequest) XXX_Size() int {
	return xxx_messageInfo_ControlRequest.Size(m)
}
func (m *ControlRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ControlRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ControlRequest proto.InternalMessageInfo

func (m *ControlRequest) GetOid() string {
	if m != nil {
		return m.Oid
	}
	return ""
}

func (m *ControlRequest) GetTime() *Time {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *ControlRequest) GetCircle() *Circle {
	if m != nil {
		return m.Circle
	}
	return nil
}

type Time struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	Interval             int64    `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{6}
}

func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (m *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(m, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *Time) GetInterval() int64 {
	if m != nil {
		return m.Interval
	}
	return 0
}

type Circle struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Radius               float64  `protobuf:"fixed64,3,opt,name=radius,proto3" json:"radius,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Circle) Reset()         { *m = Circle{} }
func (m *Circle) String() string { return proto.CompactTextString(m) }
func (*Circle) ProtoMessage()    {}
func (*Circle) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{7}
}

func (m *Circle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Circle.Unmarshal(m, b)
}
func (m *Circle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Circle.Marshal(b, m, deterministic)
}
func (m *Circle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Circle.Merge(m, src)
}
func (m *Circle) XXX_Size() int {
	return xxx_messageInfo_Circle.Size(m)
}
func (m *Circle) XXX_DiscardUnknown() {
	xxx_messageInfo_Circle.DiscardUnknown(m)
}

var xxx_messageInfo_Circle proto.InternalMessageInfo

func (m *Circle) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Circle) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

func (m *Circle) GetRadius() float64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

type OsmResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OsmResponse) Reset()         { *m = OsmResponse{} }
func (m *OsmResponse) String() string { return proto.CompactTextString(m) }
func (*OsmResponse) ProtoMessage()    {}
func (*OsmResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{8}
}

func (m *OsmResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OsmResponse.Unmarshal(m, b)
}
func (m *OsmResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OsmResponse.Marshal(b, m, deterministic)
}
func (m *OsmResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OsmResponse.Merge(m, src)
}
func (m *OsmResponse) XXX_Size() int {
	return xxx_messageInfo_OsmResponse.Size(m)
}
func (m *OsmResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OsmResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OsmResponse proto.InternalMessageInfo

func (m *OsmResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type GeocodeRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeocodeRequest) Reset()         { *m = GeocodeRequest{} }
func (m *GeocodeRequest) String() string { return proto.CompactTextString(m) }
func (*GeocodeRequest) ProtoMessage()    {}
func (*GeocodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{9}
}

func (m *GeocodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeocodeRequest.Unmarshal(m, b)
}
func (m *GeocodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeocodeRequest.Marshal(b, m, deterministic)
}
func (m *GeocodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeocodeRequest.Merge(m, src)
}
func (m *GeocodeRequest) XXX_Size() int {
	return xxx_messageInfo_GeocodeRequest.Size(m)
}
func (m *GeocodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeocodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeocodeRequest proto.InternalMessageInfo

func (m *GeocodeRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type Point struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon                  float64  `protobuf:"fixed64,2,opt,name=lon,proto3" json:"lon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{10}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Point) GetLon() float64 {
	if m != nil {
		return m.Lon
	}
	return 0
}

type GeocodeReverseRequest struct {
	Point                *Point   `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeocodeReverseRequest) Reset()         { *m = GeocodeReverseRequest{} }
func (m *GeocodeReverseRequest) String() string { return proto.CompactTextString(m) }
func (*GeocodeReverseRequest) ProtoMessage()    {}
func (*GeocodeReverseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{11}
}

func (m *GeocodeReverseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeocodeReverseRequest.Unmarshal(m, b)
}
func (m *GeocodeReverseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeocodeReverseRequest.Marshal(b, m, deterministic)
}
func (m *GeocodeReverseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeocodeReverseRequest.Merge(m, src)
}
func (m *GeocodeReverseRequest) XXX_Size() int {
	return xxx_messageInfo_GeocodeReverseRequest.Size(m)
}
func (m *GeocodeReverseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GeocodeReverseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GeocodeReverseRequest proto.InternalMessageInfo

func (m *GeocodeReverseRequest) GetPoint() *Point {
	if m != nil {
		return m.Point
	}
	return nil
}

type GetRouteRequest struct {
	Coordinates          []*Point `protobuf:"bytes,1,rep,name=coordinates,proto3" json:"coordinates,omitempty"`
	Options              []byte   `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRouteRequest) Reset()         { *m = GetRouteRequest{} }
func (m *GetRouteRequest) String() string { return proto.CompactTextString(m) }
func (*GetRouteRequest) ProtoMessage()    {}
func (*GetRouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{12}
}

func (m *GetRouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRouteRequest.Unmarshal(m, b)
}
func (m *GetRouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRouteRequest.Marshal(b, m, deterministic)
}
func (m *GetRouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRouteRequest.Merge(m, src)
}
func (m *GetRouteRequest) XXX_Size() int {
	return xxx_messageInfo_GetRouteRequest.Size(m)
}
func (m *GetRouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRouteRequest proto.InternalMessageInfo

func (m *GetRouteRequest) GetCoordinates() []*Point {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *GetRouteRequest) GetOptions() []byte {
	if m != nil {
		return m.Options
	}
	return nil
}

type IndoorCircle struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float64  `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	Radius               float64  `protobuf:"fixed64,4,opt,name=radius,proto3" json:"radius,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndoorCircle) Reset()         { *m = IndoorCircle{} }
func (m *IndoorCircle) String() string { return proto.CompactTextString(m) }
func (*IndoorCircle) ProtoMessage()    {}
func (*IndoorCircle) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{13}
}

func (m *IndoorCircle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndoorCircle.Unmarshal(m, b)
}
func (m *IndoorCircle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndoorCircle.Marshal(b, m, deterministic)
}
func (m *IndoorCircle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndoorCircle.Merge(m, src)
}
func (m *IndoorCircle) XXX_Size() int {
	return xxx_messageInfo_IndoorCircle.Size(m)
}
func (m *IndoorCircle) XXX_DiscardUnknown() {
	xxx_messageInfo_IndoorCircle.DiscardUnknown(m)
}

var xxx_messageInfo_IndoorCircle proto.InternalMessageInfo

func (m *IndoorCircle) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *IndoorCircle) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *IndoorCircle) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

func (m *IndoorCircle) GetRadius() float64 {
	if m != nil {
		return m.Radius
	}
	return 0
}

type Zone struct {
	Circle               *Circle       `protobuf:"bytes,1,opt,name=circle,proto3" json:"circle,omitempty"`
	IndoorCircle         *IndoorCircle `protobuf:"bytes,2,opt,name=indoor_circle,json=indoorCircle,proto3" json:"indoor_circle,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Zone) Reset()         { *m = Zone{} }
func (m *Zone) String() string { return proto.CompactTextString(m) }
func (*Zone) ProtoMessage()    {}
func (*Zone) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{14}
}

func (m *Zone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Zone.Unmarshal(m, b)
}
func (m *Zone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Zone.Marshal(b, m, deterministic)
}
func (m *Zone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Zone.Merge(m, src)
}
func (m *Zone) XXX_Size() int {
	return xxx_messageInfo_Zone.Size(m)
}
func (m *Zone) XXX_DiscardUnknown() {
	xxx_messageInfo_Zone.DiscardUnknown(m)
}

var xxx_messageInfo_Zone proto.InternalMessageInfo

func (m *Zone) GetCircle() *Circle {
	if m != nil {
		return m.Circle
	}
	return nil
}

func (m *Zone) GetIndoorCircle() *IndoorCircle {
	if m != nil {
		return m.IndoorCircle
	}
	return nil
}

type IndoorPoint struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float64  `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndoorPoint) Reset()         { *m = IndoorPoint{} }
func (m *IndoorPoint) String() string { return proto.CompactTextString(m) }
func (*IndoorPoint) ProtoMessage()    {}
func (*IndoorPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{15}
}

func (m *IndoorPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndoorPoint.Unmarshal(m, b)
}
func (m *IndoorPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndoorPoint.Marshal(b, m, deterministic)
}
func (m *IndoorPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndoorPoint.Merge(m, src)
}
func (m *IndoorPoint) XXX_Size() int {
	return xxx_messageInfo_IndoorPoint.Size(m)
}
func (m *IndoorPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_IndoorPoint.DiscardUnknown(m)
}

var xxx_messageInfo_IndoorPoint proto.InternalMessageInfo

func (m *IndoorPoint) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *IndoorPoint) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *IndoorPoint) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Position struct {
	Location             *Point       `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	IndoorLocation       *IndoorPoint `protobuf:"bytes,2,opt,name=indoor_location,json=indoorLocation,proto3" json:"indoor_location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{16}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetLocation() *Point {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Position) GetIndoorLocation() *IndoorPoint {
	if m != nil {
		return m.IndoorLocation
	}
	return nil
}

type CheckInRequest struct {
	Position             *Position `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Zone                 *Zone     `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CheckInRequest) Reset()         { *m = CheckInRequest{} }
func (m *CheckInRequest) String() string { return proto.CompactTextString(m) }
func (*CheckInRequest) ProtoMessage()    {}
func (*CheckInRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{17}
}

func (m *CheckInRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckInRequest.Unmarshal(m, b)
}
func (m *CheckInRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckInRequest.Marshal(b, m, deterministic)
}
func (m *CheckInRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckInRequest.Merge(m, src)
}
func (m *CheckInRequest) XXX_Size() int {
	return xxx_messageInfo_CheckInRequest.Size(m)
}
func (m *CheckInRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckInRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckInRequest proto.InternalMessageInfo

func (m *CheckInRequest) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *CheckInRequest) GetZone() *Zone {
	if m != nil {
		return m.Zone
	}
	return nil
}

type CheckInResponse struct {
	In                   bool     `protobuf:"varint,1,opt,name=in,proto3" json:"in,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckInResponse) Reset()         { *m = CheckInResponse{} }
func (m *CheckInResponse) String() string { return proto.CompactTextString(m) }
func (*CheckInResponse) ProtoMessage()    {}
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dd0c87ff6803edb, []int{18}
}

func (m *CheckInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckInResponse.Unmarshal(m, b)
}
func (m *CheckInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckInResponse.Marshal(b, m, deterministic)
}
func (m *CheckInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckInResponse.Merge(m, src)
}
func (m *CheckInResponse) XXX_Size() int {
	return xxx_messageInfo_CheckInResponse.Size(m)
}
func (m *CheckInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckInResponse proto.InternalMessageInfo

func (m *CheckInResponse) GetIn() bool {
	if m != nil {
		return m.In
	}
	return false
}

func init() {
	proto.RegisterType((*EmptyResponse)(nil), "ric.geo.EmptyResponse")
	proto.RegisterType((*WatchRequest)(nil), "ric.geo.WatchRequest")
	proto.RegisterType((*RpeatedFence)(nil), "ric.geo.RpeatedFence")
	proto.RegisterType((*Fence)(nil), "ric.geo.Fence")
	proto.RegisterType((*RepeatedRoute)(nil), "ric.geo.RepeatedRoute")
	proto.RegisterType((*ControlRequest)(nil), "ric.geo.ControlRequest")
	proto.RegisterType((*Time)(nil), "ric.geo.Time")
	proto.RegisterType((*Circle)(nil), "ric.geo.Circle")
	proto.RegisterType((*OsmResponse)(nil), "ric.geo.OsmResponse")
	proto.RegisterType((*GeocodeRequest)(nil), "ric.geo.GeocodeRequest")
	proto.RegisterType((*Point)(nil), "ric.geo.Point")
	proto.RegisterType((*GeocodeReverseRequest)(nil), "ric.geo.GeocodeReverseRequest")
	proto.RegisterType((*GetRouteRequest)(nil), "ric.geo.GetRouteRequest")
	proto.RegisterType((*IndoorCircle)(nil), "ric.geo.IndoorCircle")
	proto.RegisterType((*Zone)(nil), "ric.geo.Zone")
	proto.RegisterType((*IndoorPoint)(nil), "ric.geo.IndoorPoint")
	proto.RegisterType((*Position)(nil), "ric.geo.Position")
	proto.RegisterType((*CheckInRequest)(nil), "ric.geo.CheckInRequest")
	proto.RegisterType((*CheckInResponse)(nil), "ric.geo.CheckInResponse")
}

func init() { proto.RegisterFile("ric-geo/ricgeo.proto", fileDescriptor_7dd0c87ff6803edb) }

var fileDescriptor_7dd0c87ff6803edb = []byte{
	// 856 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x6d, 0x6f, 0x1b, 0x45,
	0x10, 0xe6, 0x7c, 0xf6, 0xf9, 0x3c, 0x7e, 0x23, 0x2b, 0xb7, 0x35, 0x96, 0x80, 0x78, 0x85, 0x4a,
	0x04, 0xaa, 0x5b, 0x19, 0x09, 0x2a, 0x43, 0x8b, 0x48, 0x68, 0x83, 0x25, 0xa4, 0x44, 0x4b, 0x25,
	0xa4, 0x0a, 0x14, 0x5d, 0xee, 0x16, 0x67, 0x15, 0x7b, 0xf7, 0x72, 0xb7, 0x8e, 0xe2, 0x7c, 0xe7,
	0xcf, 0xf0, 0x37, 0xf8, 0x63, 0x68, 0x5f, 0xee, 0xbc, 0x4e, 0x62, 0x94, 0xc0, 0xb7, 0x99, 0x9d,
	0x79, 0x9e, 0x99, 0x9b, 0x9d, 0x7d, 0x74, 0xd0, 0xcb, 0x58, 0xfc, 0x6c, 0x46, 0xc5, 0xf3, 0x8c,
	0xc5, 0x33, 0x2a, 0x46, 0x69, 0x26, 0xa4, 0x40, 0xf5, 0x8c, 0xc5, 0xa3, 0x19, 0x15, 0xb8, 0x0b,
	0xed, 0x37, 0x8b, 0x54, 0xae, 0x08, 0xcd, 0x53, 0xc1, 0x73, 0x8a, 0xff, 0xf2, 0xa0, 0xf5, 0x6b,
	0x24, 0xe3, 0x33, 0x42, 0x2f, 0x96, 0x34, 0x97, 0xe8, 0x43, 0xf0, 0x05, 0x4b, 0xfa, 0xde, 0xae,
	0xb7, 0xd7, 0x20, 0xca, 0x44, 0x1f, 0x03, 0xd0, 0x4b, 0xca, 0xe5, 0x89, 0x5c, 0xa5, 0xb4, 0x5f,
	0xd1, 0x81, 0x86, 0x3e, 0x79, 0xb7, 0x4a, 0x29, 0x7a, 0x0e, 0xc1, 0x1f, 0x94, 0xc7, 0x34, 0xef,
	0xfb, 0xbb, 0xde, 0x5e, 0x73, 0xfc, 0x68, 0x64, 0x8b, 0x8d, 0x48, 0x4a, 0x23, 0x49, 0x93, 0xb7,
	0x2a, 0xfa, 0xd3, 0x07, 0xc4, 0xa6, 0xa1, 0x17, 0x10, 0x64, 0x62, 0x29, 0x69, 0xde, 0xaf, 0x6a,
	0xc0, 0xe3, 0x35, 0x80, 0x1a, 0x04, 0x51, 0x61, 0x85, 0x30, 0x79, 0xfb, 0x01, 0x54, 0x55, 0x6d,
	0xfc, 0x35, 0xb4, 0x5c, 0x4e, 0xf4, 0xb4, 0x2c, 0xed, 0xed, 0xfa, 0x7b, 0xcd, 0x71, 0xa7, 0x64,
	0xd2, 0xf1, 0xa2, 0x22, 0xfe, 0x0d, 0x6a, 0x06, 0xf0, 0x29, 0x34, 0x67, 0x54, 0xe8, 0xd3, 0x93,
	0xf2, 0x23, 0xa1, 0x38, 0x9a, 0x26, 0xe8, 0x23, 0x08, 0xf3, 0xb3, 0x28, 0xd5, 0x51, 0xf3, 0xa5,
	0x75, 0xed, 0x4f, 0x13, 0xf4, 0x04, 0xea, 0x99, 0x10, 0x0b, 0x15, 0xf1, 0x75, 0x24, 0x50, 0xee,
	0x34, 0xc1, 0x43, 0x68, 0x6f, 0x34, 0xae, 0x46, 0xc8, 0x12, 0xd3, 0x53, 0x83, 0x28, 0x13, 0x73,
	0xe8, 0x1c, 0x08, 0x2e, 0x33, 0x31, 0xdf, 0x3e, 0xe6, 0x21, 0x54, 0x25, 0x5b, 0x98, 0x01, 0x37,
	0xc7, 0xed, 0xf2, 0x53, 0xde, 0xb1, 0x05, 0x25, 0x3a, 0x84, 0x3e, 0x87, 0x20, 0x66, 0x59, 0x3c,
	0xa7, 0x76, 0xd4, 0xdd, 0x32, 0xe9, 0x40, 0x1f, 0x13, 0x1b, 0xc6, 0x2f, 0xa1, 0xaa, 0x60, 0xa8,
	0x07, 0xb5, 0x5c, 0x46, 0x99, 0xd4, 0x75, 0x7c, 0x62, 0x1c, 0x34, 0x80, 0x90, 0x71, 0x49, 0xb3,
	0xcb, 0x68, 0xae, 0xab, 0xf9, 0xa4, 0xf4, 0xf1, 0x8f, 0x10, 0x18, 0x2e, 0xd5, 0xe1, 0x3c, 0x32,
	0x48, 0x8f, 0x28, 0x53, 0x9f, 0x08, 0xae, 0x21, 0xea, 0x44, 0x70, 0xf4, 0x18, 0x82, 0x2c, 0x4a,
	0xd8, 0xd2, 0xdc, 0xbd, 0x47, 0xac, 0x87, 0x87, 0xd0, 0x3c, 0xca, 0x17, 0xc5, 0x92, 0x21, 0x04,
	0xd5, 0x24, 0x92, 0x91, 0xe6, 0x6a, 0x11, 0x6d, 0xe3, 0xa7, 0xd0, 0x39, 0xa4, 0x22, 0x16, 0x09,
	0x2d, 0x46, 0xd2, 0x83, 0xda, 0xc5, 0x92, 0x66, 0x2b, 0x3b, 0x14, 0xe3, 0xe0, 0x2f, 0xa1, 0x76,
	0x2c, 0x18, 0x97, 0xf7, 0xe9, 0x07, 0xbf, 0x82, 0x47, 0x25, 0xe9, 0x25, 0xcd, 0xf2, 0x92, 0xfb,
	0x33, 0xa8, 0xa5, 0x8a, 0x45, 0xc3, 0xdd, 0x45, 0xd1, 0xdc, 0xc4, 0x04, 0xf1, 0xef, 0xd0, 0x3d,
	0xa4, 0x52, 0x5f, 0x62, 0x01, 0x7c, 0x01, 0xcd, 0x58, 0x88, 0x2c, 0x61, 0x3c, 0x92, 0x77, 0xec,
	0x99, 0x81, 0xbb, 0x29, 0xa8, 0x0f, 0x75, 0x91, 0x4a, 0x26, 0x78, 0xae, 0x3b, 0x6b, 0x91, 0xc2,
	0xc5, 0xc7, 0xd0, 0x9a, 0xf2, 0x44, 0x88, 0xcc, 0x4e, 0xb8, 0x05, 0xde, 0x95, 0xfd, 0x1e, 0xef,
	0x4a, 0x79, 0x2b, 0xfb, 0x2d, 0xde, 0x4a, 0x79, 0xd7, 0x76, 0xa8, 0xde, 0xb5, 0x33, 0xe7, 0xea,
	0xc6, 0x9c, 0xcf, 0xa1, 0xfa, 0x5e, 0x70, 0x77, 0x31, 0xbc, 0x7f, 0x5d, 0x0c, 0x34, 0x81, 0x36,
	0xd3, 0x2d, 0x9c, 0xd8, 0xfc, 0xca, 0x8d, 0x37, 0xeb, 0x36, 0x48, 0x5a, 0xcc, 0xf1, 0xf0, 0x37,
	0xd0, 0x34, 0x51, 0x73, 0x1f, 0xf7, 0xee, 0x1e, 0x2f, 0x21, 0x3c, 0x16, 0x39, 0x53, 0x43, 0x40,
	0x5f, 0x40, 0x38, 0x17, 0x71, 0xa4, 0xec, 0x2d, 0x77, 0x51, 0xc6, 0xd1, 0x2b, 0xe8, 0xda, 0x66,
	0x4b, 0x88, 0x69, 0xb7, 0x77, 0xa3, 0x5d, 0x03, 0xec, 0x98, 0xe4, 0x9f, 0x6d, 0x2e, 0x3e, 0x85,
	0xce, 0xc1, 0x19, 0x8d, 0xcf, 0xa7, 0xbc, 0xb8, 0xcc, 0x67, 0x10, 0xa6, 0xb6, 0x11, 0x5b, 0x7c,
	0xc7, 0x29, 0x6e, 0x02, 0xa4, 0x4c, 0x51, 0x2f, 0xf2, 0x5a, 0xf0, 0xdb, 0x2f, 0x52, 0x8d, 0x9c,
	0xe8, 0x10, 0x1e, 0x42, 0xb7, 0xac, 0x61, 0x97, 0xbd, 0x03, 0x15, 0x66, 0xe8, 0x43, 0x52, 0x61,
	0x7c, 0xfc, 0xa7, 0x0f, 0x35, 0xad, 0xb0, 0xe8, 0x35, 0xb4, 0xb5, 0x71, 0x68, 0xf5, 0x06, 0xad,
	0xc7, 0xee, 0x4a, 0xf0, 0x60, 0x2d, 0x88, 0x1b, 0x5a, 0x8d, 0xf6, 0x61, 0xe7, 0x17, 0x29, 0xd2,
	0xff, 0xc5, 0x31, 0x81, 0x86, 0xc9, 0x13, 0x62, 0xf1, 0x50, 0xec, 0x6b, 0x68, 0x97, 0xf5, 0xff,
	0x0b, 0xfe, 0x5b, 0x00, 0x8b, 0x55, 0x2a, 0xf9, 0x40, 0xf0, 0xf7, 0xd0, 0x71, 0x8a, 0x3f, 0x9c,
	0x60, 0x7c, 0x04, 0x3b, 0x3f, 0x48, 0x49, 0x79, 0x12, 0xf1, 0x98, 0x5a, 0x35, 0x46, 0x13, 0xa8,
	0x17, 0xe6, 0x93, 0xf5, 0x9b, 0xd9, 0x90, 0xea, 0xad, 0x84, 0x7f, 0x7b, 0xe0, 0x1f, 0xe5, 0x0b,
	0xf4, 0x12, 0xea, 0x56, 0x74, 0x1c, 0x8e, 0x4d, 0x6d, 0x1b, 0xac, 0x37, 0xd6, 0xd5, 0xc5, 0xb7,
	0x8e, 0x06, 0x6a, 0xb9, 0x42, 0x9f, 0xdc, 0x26, 0x70, 0x75, 0x6c, 0x0b, 0xcf, 0x04, 0xc2, 0x42,
	0xb7, 0x50, 0xdf, 0x61, 0xd8, 0x90, 0xb2, 0xbb, 0xb1, 0xe3, 0x37, 0x50, 0xd3, 0x1b, 0x8c, 0xbe,
	0x83, 0xba, 0x5d, 0x65, 0x77, 0x14, 0x1b, 0x0f, 0x68, 0xd0, 0xbf, 0x1d, 0x30, 0x34, 0xfb, 0xe1,
	0xfb, 0xc0, 0xfc, 0x71, 0x9c, 0x06, 0xfa, 0x97, 0xe3, 0xab, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xbc, 0x76, 0xcd, 0x13, 0x8a, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WatchClient is the client API for Watch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WatchClient interface {
	WatchGeofence(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	StopWatchGeofence(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	WatchRoom(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	StopWatchRoom(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	WatchRoute(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	StopWatchRoute(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type watchClient struct {
	cc *grpc.ClientConn
}

func NewWatchClient(cc *grpc.ClientConn) WatchClient {
	return &watchClient{cc}
}

func (c *watchClient) WatchGeofence(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/ric.geo.Watch/WatchGeofence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClient) StopWatchGeofence(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/ric.geo.Watch/StopWatchGeofence", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClient) WatchRoom(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/ric.geo.Watch/WatchRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClient) StopWatchRoom(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/ric.geo.Watch/StopWatchRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClient) WatchRoute(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/ric.geo.Watch/WatchRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchClient) StopWatchRoute(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/ric.geo.Watch/StopWatchRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WatchServer is the server API for Watch service.
type WatchServer interface {
	WatchGeofence(context.Context, *WatchRequest) (*EmptyResponse, error)
	StopWatchGeofence(context.Context, *WatchRequest) (*EmptyResponse, error)
	WatchRoom(context.Context, *WatchRequest) (*EmptyResponse, error)
	StopWatchRoom(context.Context, *WatchRequest) (*EmptyResponse, error)
	WatchRoute(context.Context, *WatchRequest) (*EmptyResponse, error)
	StopWatchRoute(context.Context, *WatchRequest) (*EmptyResponse, error)
}

func RegisterWatchServer(s *grpc.Server, srv WatchServer) {
	s.RegisterService(&_Watch_serviceDesc, srv)
}

func _Watch_WatchGeofence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchServer).WatchGeofence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ric.geo.Watch/WatchGeofence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchServer).WatchGeofence(ctx, req.(*WatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Watch_StopWatchGeofence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchServer).StopWatchGeofence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ric.geo.Watch/StopWatchGeofence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchServer).StopWatchGeofence(ctx, req.(*WatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Watch_WatchRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchServer).WatchRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ric.geo.Watch/WatchRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchServer).WatchRoom(ctx, req.(*WatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Watch_StopWatchRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchServer).StopWatchRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ric.geo.Watch/StopWatchRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchServer).StopWatchRoom(ctx, req.(*WatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Watch_WatchRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchServer).WatchRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ric.geo.Watch/WatchRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchServer).WatchRoute(ctx, req.(*WatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Watch_StopWatchRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchServer).StopWatchRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ric.geo.Watch/StopWatchRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchServer).StopWatchRoute(ctx, req.(*WatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Watch_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ric.geo.Watch",
	HandlerType: (*WatchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WatchGeofence",
			Handler:    _Watch_WatchGeofence_Handler,
		},
		{
			MethodName: "StopWatchGeofence",
			Handler:    _Watch_StopWatchGeofence_Handler,
		},
		{
			MethodName: "WatchRoom",
			Handler:    _Watch_WatchRoom_Handler,
		},
		{
			MethodName: "StopWatchRoom",
			Handler:    _Watch_StopWatchRoom_Handler,
		},
		{
			MethodName: "WatchRoute",
			Handler:    _Watch_WatchRoute_Handler,
		},
		{
			MethodName: "StopWatchRoute",
			Handler:    _Watch_StopWatchRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ric-geo/ricgeo.proto",
}

// AttendanceControlClient is the client API for AttendanceControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AttendanceControlClient interface {
	Control(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type attendanceControlClient struct {
	cc *grpc.ClientConn
}

func NewAttendanceControlClient(cc *grpc.ClientConn) AttendanceControlClient {
	return &attendanceControlClient{cc}
}

func (c *attendanceControlClient) Control(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/ric.geo.AttendanceControl/Control", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttendanceControlServer is the server API for AttendanceControl service.
type AttendanceControlServer interface {
	Control(context.Context, *ControlRequest) (*EmptyResponse, error)
}

func RegisterAttendanceControlServer(s *grpc.Server, srv AttendanceControlServer) {
	s.RegisterService(&_AttendanceControl_serviceDesc, srv)
}

func _AttendanceControl_Control_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttendanceControlServer).Control(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ric.geo.AttendanceControl/Control",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttendanceControlServer).Control(ctx, req.(*ControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AttendanceControl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ric.geo.AttendanceControl",
	HandlerType: (*AttendanceControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Control",
			Handler:    _AttendanceControl_Control_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ric-geo/ricgeo.proto",
}

// OsmClient is the client API for Osm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OsmClient interface {
	Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*OsmResponse, error)
	GeocodeReverse(ctx context.Context, in *GeocodeReverseRequest, opts ...grpc.CallOption) (*OsmResponse, error)
	GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*OsmResponse, error)
}

type osmClient struct {
	cc *grpc.ClientConn
}

func NewOsmClient(cc *grpc.ClientConn) OsmClient {
	return &osmClient{cc}
}

func (c *osmClient) Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*OsmResponse, error) {
	out := new(OsmResponse)
	err := c.cc.Invoke(ctx, "/ric.geo.Osm/Geocode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osmClient) GeocodeReverse(ctx context.Context, in *GeocodeReverseRequest, opts ...grpc.CallOption) (*OsmResponse, error) {
	out := new(OsmResponse)
	err := c.cc.Invoke(ctx, "/ric.geo.Osm/GeocodeReverse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osmClient) GetRoute(ctx context.Context, in *GetRouteRequest, opts ...grpc.CallOption) (*OsmResponse, error) {
	out := new(OsmResponse)
	err := c.cc.Invoke(ctx, "/ric.geo.Osm/GetRoute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OsmServer is the server API for Osm service.
type OsmServer interface {
	Geocode(context.Context, *GeocodeRequest) (*OsmResponse, error)
	GeocodeReverse(context.Context, *GeocodeReverseRequest) (*OsmResponse, error)
	GetRoute(context.Context, *GetRouteRequest) (*OsmResponse, error)
}

func RegisterOsmServer(s *grpc.Server, srv OsmServer) {
	s.RegisterService(&_Osm_serviceDesc, srv)
}

func _Osm_Geocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmServer).Geocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ric.geo.Osm/Geocode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmServer).Geocode(ctx, req.(*GeocodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Osm_GeocodeReverse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocodeReverseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmServer).GeocodeReverse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ric.geo.Osm/GeocodeReverse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmServer).GeocodeReverse(ctx, req.(*GeocodeReverseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Osm_GetRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmServer).GetRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ric.geo.Osm/GetRoute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmServer).GetRoute(ctx, req.(*GetRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Osm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ric.geo.Osm",
	HandlerType: (*OsmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Geocode",
			Handler:    _Osm_Geocode_Handler,
		},
		{
			MethodName: "GeocodeReverse",
			Handler:    _Osm_GeocodeReverse_Handler,
		},
		{
			MethodName: "GetRoute",
			Handler:    _Osm_GetRoute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ric-geo/ricgeo.proto",
}

// CheckClient is the client API for Check service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CheckClient interface {
	CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error)
}

type checkClient struct {
	cc *grpc.ClientConn
}

func NewCheckClient(cc *grpc.ClientConn) CheckClient {
	return &checkClient{cc}
}

func (c *checkClient) CheckIn(ctx context.Context, in *CheckInRequest, opts ...grpc.CallOption) (*CheckInResponse, error) {
	out := new(CheckInResponse)
	err := c.cc.Invoke(ctx, "/ric.geo.Check/CheckIn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckServer is the server API for Check service.
type CheckServer interface {
	CheckIn(context.Context, *CheckInRequest) (*CheckInResponse, error)
}

func RegisterCheckServer(s *grpc.Server, srv CheckServer) {
	s.RegisterService(&_Check_serviceDesc, srv)
}

func _Check_CheckIn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckServer).CheckIn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ric.geo.Check/CheckIn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckServer).CheckIn(ctx, req.(*CheckInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Check_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ric.geo.Check",
	HandlerType: (*CheckServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckIn",
			Handler:    _Check_CheckIn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ric-geo/ricgeo.proto",
}
