// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ric-smpp/ric-smpp.proto

package ricsmpp

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusResponse_State int32

const (
	StatusResponse_UNKNOWN    StatusResponse_State = 0
	StatusResponse_SCHEDULE   StatusResponse_State = 1
	StatusResponse_SEND_ERROR StatusResponse_State = 2
	StatusResponse_SENT       StatusResponse_State = 3
	StatusResponse_ERROR      StatusResponse_State = 4
	StatusResponse_NOT_FOUND  StatusResponse_State = 5
)

var StatusResponse_State_name = map[int32]string{
	0: "UNKNOWN",
	1: "SCHEDULE",
	2: "SEND_ERROR",
	3: "SENT",
	4: "ERROR",
	5: "NOT_FOUND",
}

var StatusResponse_State_value = map[string]int32{
	"UNKNOWN":    0,
	"SCHEDULE":   1,
	"SEND_ERROR": 2,
	"SENT":       3,
	"ERROR":      4,
	"NOT_FOUND":  5,
}

func (x StatusResponse_State) String() string {
	return proto.EnumName(StatusResponse_State_name, int32(x))
}

func (StatusResponse_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d4a028490178e0d7, []int{4, 0}
}

type UserContext struct {
	GroupId              string   `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SpanId               string   `protobuf:"bytes,3,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserContext) Reset()         { *m = UserContext{} }
func (m *UserContext) String() string { return proto.CompactTextString(m) }
func (*UserContext) ProtoMessage()    {}
func (*UserContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4a028490178e0d7, []int{0}
}

func (m *UserContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserContext.Unmarshal(m, b)
}
func (m *UserContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserContext.Marshal(b, m, deterministic)
}
func (m *UserContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserContext.Merge(m, src)
}
func (m *UserContext) XXX_Size() int {
	return xxx_messageInfo_UserContext.Size(m)
}
func (m *UserContext) XXX_DiscardUnknown() {
	xxx_messageInfo_UserContext.DiscardUnknown(m)
}

var xxx_messageInfo_UserContext proto.InternalMessageInfo

func (m *UserContext) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

func (m *UserContext) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserContext) GetSpanId() string {
	if m != nil {
		return m.SpanId
	}
	return ""
}

type SendRequest struct {
	Ctx                  *UserContext `protobuf:"bytes,1,opt,name=ctx,proto3" json:"ctx,omitempty"`
	GatewayId            string       `protobuf:"bytes,2,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	Phone                string       `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Message              string       `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4a028490178e0d7, []int{1}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetCtx() *UserContext {
	if m != nil {
		return m.Ctx
	}
	return nil
}

func (m *SendRequest) GetGatewayId() string {
	if m != nil {
		return m.GatewayId
	}
	return ""
}

func (m *SendRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SendRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type SendResponse struct {
	MessageId            string   `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4a028490178e0d7, []int{2}
}

func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (m *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(m, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func (m *SendResponse) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

type StatusRequest struct {
	GatewayId            string   `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	MessageId            string   `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4a028490178e0d7, []int{3}
}

func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (m *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(m, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

func (m *StatusRequest) GetGatewayId() string {
	if m != nil {
		return m.GatewayId
	}
	return ""
}

func (m *StatusRequest) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

type StatusResponse struct {
	State                StatusResponse_State       `protobuf:"varint,1,opt,name=state,proto3,enum=ric.smpp.StatusResponse_State" json:"state,omitempty"`
	Description          string                     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	SmppStatus           *StatusResponse_SMPPStatus `protobuf:"bytes,3,opt,name=smpp_status,json=smppStatus,proto3" json:"smpp_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4a028490178e0d7, []int{4}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetState() StatusResponse_State {
	if m != nil {
		return m.State
	}
	return StatusResponse_UNKNOWN
}

func (m *StatusResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *StatusResponse) GetSmppStatus() *StatusResponse_SMPPStatus {
	if m != nil {
		return m.SmppStatus
	}
	return nil
}

type StatusResponse_SMPPStatus struct {
	MsgId                string   `protobuf:"bytes,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	MsgState             string   `protobuf:"bytes,2,opt,name=msg_state,json=msgState,proto3" json:"msg_state,omitempty"`
	FinalDate            string   `protobuf:"bytes,3,opt,name=final_date,json=finalDate,proto3" json:"final_date,omitempty"`
	ErrCode              int32    `protobuf:"varint,4,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse_SMPPStatus) Reset()         { *m = StatusResponse_SMPPStatus{} }
func (m *StatusResponse_SMPPStatus) String() string { return proto.CompactTextString(m) }
func (*StatusResponse_SMPPStatus) ProtoMessage()    {}
func (*StatusResponse_SMPPStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4a028490178e0d7, []int{4, 0}
}

func (m *StatusResponse_SMPPStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse_SMPPStatus.Unmarshal(m, b)
}
func (m *StatusResponse_SMPPStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse_SMPPStatus.Marshal(b, m, deterministic)
}
func (m *StatusResponse_SMPPStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse_SMPPStatus.Merge(m, src)
}
func (m *StatusResponse_SMPPStatus) XXX_Size() int {
	return xxx_messageInfo_StatusResponse_SMPPStatus.Size(m)
}
func (m *StatusResponse_SMPPStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse_SMPPStatus.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse_SMPPStatus proto.InternalMessageInfo

func (m *StatusResponse_SMPPStatus) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *StatusResponse_SMPPStatus) GetMsgState() string {
	if m != nil {
		return m.MsgState
	}
	return ""
}

func (m *StatusResponse_SMPPStatus) GetFinalDate() string {
	if m != nil {
		return m.FinalDate
	}
	return ""
}

func (m *StatusResponse_SMPPStatus) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func init() {
	proto.RegisterEnum("ric.smpp.StatusResponse_State", StatusResponse_State_name, StatusResponse_State_value)
	proto.RegisterType((*UserContext)(nil), "ric.smpp.UserContext")
	proto.RegisterType((*SendRequest)(nil), "ric.smpp.SendRequest")
	proto.RegisterType((*SendResponse)(nil), "ric.smpp.SendResponse")
	proto.RegisterType((*StatusRequest)(nil), "ric.smpp.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "ric.smpp.StatusResponse")
	proto.RegisterType((*StatusResponse_SMPPStatus)(nil), "ric.smpp.StatusResponse.SMPPStatus")
}

func init() {
	proto.RegisterFile("ric-smpp/ric-smpp.proto", fileDescriptor_d4a028490178e0d7)
}

var fileDescriptor_d4a028490178e0d7 = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xcd, 0x6f, 0xd3, 0x30,
	0x1c, 0xa5, 0x6d, 0xd2, 0x24, 0xbf, 0x6c, 0x55, 0x64, 0x31, 0xda, 0x0d, 0x81, 0xa6, 0x70, 0x80,
	0xcb, 0x8a, 0x54, 0xe0, 0xc4, 0x8d, 0x26, 0x88, 0x08, 0x96, 0x4e, 0xc9, 0x0a, 0xd2, 0x2e, 0x51,
	0x88, 0x4d, 0x88, 0x44, 0x3e, 0xb0, 0x5d, 0x31, 0x76, 0x44, 0xe2, 0xff, 0x46, 0xfe, 0xa8, 0xd2,
	0x16, 0xed, 0xe6, 0xf7, 0x9e, 0xf3, 0xfc, 0x7e, 0xcf, 0x0e, 0x4c, 0x69, 0x55, 0x5c, 0xb0, 0xba,
	0xeb, 0x5e, 0x6e, 0x17, 0xf3, 0x8e, 0xb6, 0xbc, 0x45, 0x36, 0xad, 0x8a, 0xb9, 0xc0, 0xfe, 0x0d,
	0xb8, 0x6b, 0x46, 0xe8, 0xb2, 0x6d, 0x38, 0xb9, 0xe5, 0xe8, 0x14, 0xec, 0x92, 0xb6, 0x9b, 0x2e,
	0xab, 0xf0, 0x6c, 0x70, 0x3e, 0x78, 0xe1, 0x24, 0x96, 0xc4, 0x11, 0x46, 0x53, 0xb0, 0x36, 0x8c,
	0x50, 0xa1, 0x0c, 0xa5, 0x32, 0x16, 0x50, 0x09, 0xac, 0xcb, 0x1b, 0x21, 0x8c, 0x94, 0x20, 0x60,
	0x84, 0xfd, 0xbf, 0x03, 0x70, 0x53, 0xd2, 0xe0, 0x84, 0xfc, 0xdc, 0x10, 0xc6, 0xd1, 0x73, 0x18,
	0x15, 0xfc, 0x56, 0xfa, 0xba, 0x8b, 0x93, 0xf9, 0x36, 0xc3, 0x7c, 0x27, 0x40, 0x22, 0x76, 0xa0,
	0x27, 0x00, 0x65, 0xce, 0xc9, 0xaf, 0xfc, 0x77, 0x7f, 0x9a, 0xa3, 0x99, 0x08, 0xa3, 0x87, 0x60,
	0x76, 0xdf, 0xdb, 0x86, 0xe8, 0xe3, 0x14, 0x40, 0x33, 0xb0, 0x6a, 0xc2, 0x58, 0x5e, 0x92, 0x99,
	0xa1, 0x92, 0x6b, 0xe8, 0x5f, 0xc0, 0x91, 0x8a, 0xc1, 0xba, 0xb6, 0x61, 0x44, 0xd8, 0x6b, 0xa9,
	0x1f, 0xd3, 0xd1, 0x4c, 0x84, 0xfd, 0x4b, 0x38, 0x4e, 0x79, 0xce, 0x37, 0x6c, 0x9b, 0x7b, 0x3f,
	0xce, 0xe0, 0x30, 0xce, 0xbe, 0xdd, 0xf0, 0xd0, 0xee, 0xcf, 0x08, 0x26, 0x5b, 0x3f, 0x1d, 0xe0,
	0x35, 0x98, 0x8c, 0xe7, 0x9c, 0x48, 0xaf, 0xc9, 0xe2, 0x69, 0x5f, 0xc5, 0xfe, 0x46, 0x09, 0x49,
	0xa2, 0x36, 0xa3, 0x73, 0x70, 0x31, 0x61, 0x05, 0xad, 0x3a, 0x5e, 0xb5, 0x8d, 0x3e, 0x68, 0x97,
	0x42, 0x01, 0xb8, 0xc2, 0x25, 0x63, 0xd2, 0x45, 0xd6, 0xe3, 0x2e, 0x9e, 0xdd, 0xef, 0x7e, 0x79,
	0x75, 0xa5, 0x29, 0x10, 0xba, 0x5a, 0x9f, 0xdd, 0x01, 0xf4, 0x0a, 0x3a, 0x81, 0x71, 0xcd, 0xca,
	0x7e, 0x70, 0xb3, 0x66, 0x65, 0x84, 0xd1, 0x63, 0x70, 0x04, 0xad, 0xc6, 0x50, 0x51, 0xec, 0x9a,
	0x95, 0x32, 0xb0, 0x68, 0xe4, 0x5b, 0xd5, 0xe4, 0x3f, 0x32, 0x2c, 0x54, 0x75, 0x4b, 0x8e, 0x64,
	0x02, 0x21, 0x9f, 0x82, 0x4d, 0x28, 0xcd, 0x8a, 0x16, 0xab, 0xab, 0x32, 0x13, 0x8b, 0x50, 0xba,
	0x6c, 0x31, 0xf1, 0x3f, 0x83, 0xa9, 0x2c, 0x5c, 0xb0, 0xd6, 0xf1, 0xc7, 0x78, 0xf5, 0x25, 0xf6,
	0x1e, 0xa0, 0x23, 0xb0, 0xd3, 0xe5, 0x87, 0x30, 0x58, 0x7f, 0x0a, 0xbd, 0x01, 0x9a, 0x00, 0xa4,
	0x61, 0x1c, 0x64, 0x61, 0x92, 0xac, 0x12, 0x6f, 0x88, 0x6c, 0x30, 0xd2, 0x30, 0xbe, 0xf6, 0x46,
	0xc8, 0x01, 0x53, 0x91, 0x06, 0x3a, 0x06, 0x27, 0x5e, 0x5d, 0x67, 0xef, 0x57, 0xeb, 0x38, 0xf0,
	0xcc, 0xc5, 0x1d, 0x18, 0x62, 0x26, 0xf4, 0x06, 0x0c, 0xf1, 0x14, 0xd0, 0xce, 0xeb, 0xdb, 0x79,
	0xa1, 0x67, 0x8f, 0x0e, 0x69, 0x7d, 0x61, 0x6f, 0x61, 0xac, 0xeb, 0x98, 0xfe, 0xdf, 0xa6, 0xfa,
	0x74, 0x76, 0x5f, 0xcd, 0xef, 0x9c, 0x1b, 0x8b, 0x56, 0x85, 0x50, 0xbe, 0x8e, 0xe5, 0xef, 0xf7,
	0xea, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x46, 0xb2, 0xfe, 0x99, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SMPPClient is the client API for SMPP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SMPPClient interface {
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type sMPPClient struct {
	cc grpc.ClientConnInterface
}

func NewSMPPClient(cc grpc.ClientConnInterface) SMPPClient {
	return &sMPPClient{cc}
}

func (c *sMPPClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/ric.smpp.SMPP/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sMPPClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/ric.smpp.SMPP/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SMPPServer is the server API for SMPP service.
type SMPPServer interface {
	Send(context.Context, *SendRequest) (*SendResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
}

// UnimplementedSMPPServer can be embedded to have forward compatible implementations.
type UnimplementedSMPPServer struct {
}

func (*UnimplementedSMPPServer) Send(ctx context.Context, req *SendRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedSMPPServer) Status(ctx context.Context, req *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}

func RegisterSMPPServer(s *grpc.Server, srv SMPPServer) {
	s.RegisterService(&_SMPP_serviceDesc, srv)
}

func _SMPP_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMPPServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ric.smpp.SMPP/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMPPServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SMPP_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMPPServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ric.smpp.SMPP/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMPPServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SMPP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ric.smpp.SMPP",
	HandlerType: (*SMPPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _SMPP_Send_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _SMPP_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ric-smpp/ric-smpp.proto",
}
